version: '3'

services:
  api1:
    image: rinha-de-backend:latest
    restart: unless-stopped
    hostname: api1
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://rinha:password@db:5432/dev?sslmode=disable
      REDIS_URL: "redis:6379"
    networks:
      - standard
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '125MB'

  api2:
    image: rinha-de-backend:latest
    restart: unless-stopped
    hostname: api2
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://rinha:password@db:5432/dev?sslmode=disable
      REDIS_URL: "redis:6379"
    networks:
      - standard
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '125MB'

  db:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rinha
      POSTGRES_DB: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - standard
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2GB'

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    networks:
      - standard
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '650MB'

  # meilisearch:
  #   image: getmeili/meilisearch:v1.3
  #   restart: unless-stopped
  #   ports:
  #     - '7700:7700'
  #   environment:
  #     MEILI_ENV: 'development'
  #   volumes:
  #     - meili_data:/meili_data
  #   networks:
  #     - standard
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: '650MB'

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    networks:
      - standard
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '100MB'

volumes:
  meili_data:

networks:
  standard:
