// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPessoas(t *testing.T) {
	t.Parallel()

	query := Pessoas()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPessoasDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPessoasQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Pessoas().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPessoasSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PessoaSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPessoasExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PessoaExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Pessoa exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PessoaExists to return true, but got false.")
	}
}

func testPessoasFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	pessoaFound, err := FindPessoa(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if pessoaFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPessoasBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Pessoas().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPessoasOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Pessoas().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPessoasAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	pessoaOne := &Pessoa{}
	pessoaTwo := &Pessoa{}
	if err = randomize.Struct(seed, pessoaOne, pessoaDBTypes, false, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}
	if err = randomize.Struct(seed, pessoaTwo, pessoaDBTypes, false, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = pessoaOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = pessoaTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Pessoas().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPessoasCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	pessoaOne := &Pessoa{}
	pessoaTwo := &Pessoa{}
	if err = randomize.Struct(seed, pessoaOne, pessoaDBTypes, false, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}
	if err = randomize.Struct(seed, pessoaTwo, pessoaDBTypes, false, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = pessoaOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = pessoaTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testPessoasInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPessoasInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(pessoaColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPessoasReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPessoasReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PessoaSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPessoasSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Pessoas().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	pessoaDBTypes = map[string]string{`ID`: `uuid`, `Nome`: `character varying`, `Apelido`: `character varying`, `Nascimento`: `character varying`, `Stack`: `ARRAYtext`}
	_             = bytes.MinRead
)

func testPessoasUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(pessoaPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(pessoaAllColumns) == len(pessoaPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPessoasSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(pessoaAllColumns) == len(pessoaPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Pessoa{}
	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, pessoaDBTypes, true, pessoaPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(pessoaAllColumns, pessoaPrimaryKeyColumns) {
		fields = pessoaAllColumns
	} else {
		fields = strmangle.SetComplement(
			pessoaAllColumns,
			pessoaPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PessoaSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPessoasUpsert(t *testing.T) {
	t.Parallel()

	if len(pessoaAllColumns) == len(pessoaPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Pessoa{}
	if err = randomize.Struct(seed, &o, pessoaDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Pessoa: %s", err)
	}

	count, err := Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, pessoaDBTypes, false, pessoaPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Pessoa struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Pessoa: %s", err)
	}

	count, err = Pessoas().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
